filepath: ""
repositories:
- name: jenkinsci
  url: https://charts.jenkins.io
- name: jx3
  url: https://charts.jenkins.io
releases:
- chart: jenkinsci/jenkins
  name: jenkins
  namespace: myjenkins9
  values:
  - values.yaml
- chart: jx3/jenkins-resources
  name: jenkins-resources
  namespace: myjenkins9
templates: {}
renderedvalues: {}
