# Source: jxboot-helmfile-resources/templates/build-bot-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "tekton-bot"
  namespace: jx
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
