# Source: jenkins-resources/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-18T11:45:33Z"
  deletionTimestamp: null
  name: 'jenkins-resources-0.0.1'
  namespace: myjenkins5
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: 1135ae662ab2003ede4ab320c97d6f10248182f1
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: github-0
            provider: jenkins.io/git-github-userid
        email: noreply@github.com
        name: GitHub
      message: 'docs: polish home page'
      sha: b09d69d17e2f9dacd8cc6dfb8f17cb27e85eb587
  gitCloneUrl: https://github.com/jenkins-x-charts/jenkins-resources.git
  gitHttpUrl: https://github.com/jenkins-x-charts/jenkins-resources
  gitOwner: jenkins-x-charts
  gitRepository: jenkins-resources
  name: 'jenkins-resources'
  releaseNotesURL: https://github.com/jenkins-x-charts/jenkins-resources/releases/tag/v0.0.1
  version: v0.0.1
status: {}
