# Source: pusher-wave/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pusher-wave
    release: "pusher-wave"
    chart: "pusher-wave-1.0.0"
    heritage: "Helm"
  name: pusher-wave-pusher-wave
  namespace: secret-infra
