# Source: jenkins-resources/templates/tekton-container-registry-auth-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tekton-container-registry-auth
  namespace: myjenkins6
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
    - name: .dockerconfigjson
      key: jstrachan-tekton2-tekton-container-registry-auth
      property: .dockerconfigjson
      version: latest
  template:
    type: kubernetes.io/dockerconfigjson
