controller:
  JCasC:
    configScripts:
      mysetup: >
        jenkins:
          systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
        jobs:
          - script: |
              multibranchPipelineJob('configuration-as-code') {
                  branchSources {
                      git {
                          id = 'jstrachan-hello-world-jenkinsfile'
                          remote('https://github.com/jstrachan/hello-world-jenkinsfile.git')
                      }
                  }
              }
