# Source: nodey545/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-14T09:43:01Z"
  deletionTimestamp: null
  name: 'nodey545-1.0.9'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 1.0.9
      sha: 1729409b48d7480ff6a190deee0aad9554a5e4f8
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 5ab9e1e6b844900d18fd1160622026c27d7a238a
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        chore: regenerated
      sha: 3291a2429fd6d123b34e4737caad17c2acdc7153
  gitHttpUrl: https://github.com/jstrachan/nodey545
  gitOwner: jstrachan
  gitRepository: nodey545
  name: 'nodey545'
  releaseNotesURL: https://github.com/jstrachan/nodey545/releases/tag/v1.0.9
  version: v1.0.9
status: {}
