# Source: nodey545/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nodey545
  labels:
    chart: "nodey545-1.0.13"
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
  namespace: jx-staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: nodey545-nodey545
