# Source: nodey545/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-14T10:08:31Z"
  deletionTimestamp: null
  name: 'nodey545-1.0.11'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 1.0.11
      sha: 8179a21d6ab87118ff87fe79f4d2e3b6009df40c
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: c61955009b8f4b3ed66610870ff48c94f88f9a35
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        chore: regenerated
      sha: 9644e1a34c02272e92ec0b2dcad805656a7200ee
  gitHttpUrl: https://github.com/jstrachan/nodey545
  gitOwner: jstrachan
  gitRepository: nodey545
  name: 'nodey545'
  releaseNotesURL: https://github.com/jstrachan/nodey545/releases/tag/v1.0.11
  version: v1.0.11
status: {}
