# Source: nodey545/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-14T09:28:13Z"
  deletionTimestamp: null
  name: 'nodey545-1.0.6'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 1.0.6
      sha: 0bca3b7ac720f3829d4508975afabcff111f8431
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: fcca12b0a1e60ed3e0c14ad93ad273d16f93e432
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        chore: regenerated
      sha: e16aa778b6b9a739557d3a9a15d509410318898f
  gitHttpUrl: https://github.com/jstrachan/nodey545
  gitOwner: jstrachan
  gitRepository: nodey545
  name: 'nodey545'
  releaseNotesURL: https://github.com/jstrachan/nodey545/releases/tag/v1.0.6
  version: v1.0.6
status: {}
