filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://chartmuseum-jx.34.105.246.143.xip.io/
- name: dev2
  url: http://jenkins-x-chartmuseum:8080
releases:
- chart: dev/nodey554
  version: 1.0.20
  name: nodey554
  values:
  - jx-values.yaml
- chart: dev/nodey545
  version: 3.0.61
  name: nodey545
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
