filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
repositories:
- name: jenkinsci
  url: https://charts.jenkins.io
releases:
- chart: jenkinsci/jenkins
  name: cheese
  namespace: cheese
  values:
  - job-values.yaml
  - values.yaml
  - ../../versionStream/charts/jenkinsci/jenkins/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
