# Source: nodey545/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-12T14:25:20Z"
  deletionTimestamp: null
  name: 'nodey545-3.0.32'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 3.0.32
      sha: 99871302e71ba47ca143bd219325d3424957ba7e
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 9afc1aa3aab9bdbafda82d240be68942284723e9
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: use GH pages
      sha: 068e610159651f1c8a45694a43174a07050f73b0
  gitHttpUrl: https://github.com/jstrachan/nodey545
  gitOwner: jstrachan
  gitRepository: nodey545
  name: 'nodey545'
  releaseNotesURL: https://github.com/jstrachan/nodey545/releases/tag/v3.0.32
  version: v3.0.32
status: {}
