# Source: nodey545/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-14T18:11:22Z"
  deletionTimestamp: null
  name: 'nodey545-3.0.51'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 3.0.51
      sha: c6b26ccd6fc3b9c59d08dc6b012221d8d52ceadd
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 95ab04f57cdaa317f213a9035a310a11c6e9d3e9
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update index.html
      sha: c936a1426d3f72a98f1ca996e93a5f6ef357f962
  gitHttpUrl: https://github.com/jstrachan/nodey545
  gitOwner: jstrachan
  gitRepository: nodey545
  name: 'nodey545'
  releaseNotesURL: https://github.com/jstrachan/nodey545/releases/tag/v3.0.51
  version: v3.0.51
status: {}
