apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        jstrachan/jx-demo-gke2-dev: true
    plank: {}
    pod_namespace: jx
    postsubmits:
      jstrachan/my-boot-jenkins:
      - agent: tekton-pipeline
        branches:
        - master
        - main
        labels:
          aadpodidbinding: tekton-bot
        name: release
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
      jstrachan/nodey534:
      - agent: tekton-pipeline
        branches:
        - master
        - main
        labels:
          aadpodidbinding: tekton-bot
        name: release
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
      jstrachan/nodey536:
      - agent: tekton-pipeline
        branches:
        - master
        - main
        labels:
          aadpodidbinding: tekton-bot
        name: release
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
      jstrachan/nodey545:
      - agent: tekton-pipeline
        branches:
        - master
        - main
        labels:
          aadpodidbinding: tekton-bot
        name: release
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
      jstrachan/nodey546:
      - agent: tekton-pipeline
        branches:
        - master
        - main
        labels:
          aadpodidbinding: tekton-bot
        name: release
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
      jstrachan/nodey553:
      - agent: tekton-pipeline
        branches:
        - master
        - main
        labels:
          aadpodidbinding: tekton-bot
        name: release
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
      jstrachan/nodey554:
      - agent: tekton-pipeline
        branches:
        - master
        - main
        labels:
          aadpodidbinding: tekton-bot
        name: release
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
    presubmits:
      jstrachan/my-boot-jenkins:
      - agent: tekton-pipeline
        always_run: true
        context: pr-build
        labels:
          aadpodidbinding: tekton-bot
        name: pr-build
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey534:
      - agent: tekton-pipeline
        always_run: true
        context: pr-build
        labels:
          aadpodidbinding: tekton-bot
        name: pr-build
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey536:
      - agent: tekton-pipeline
        always_run: true
        context: pr-build
        labels:
          aadpodidbinding: tekton-bot
        name: pr-build
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey545:
      - agent: tekton-pipeline
        always_run: true
        context: pr-build
        labels:
          aadpodidbinding: tekton-bot
        name: pr-build
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey546:
      - agent: tekton-pipeline
        always_run: true
        context: pr-build
        labels:
          aadpodidbinding: tekton-bot
        name: pr-build
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey553:
      - agent: tekton-pipeline
        always_run: true
        context: pr-build
        labels:
          aadpodidbinding: tekton-bot
        name: pr-build
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey554:
      - agent: tekton-pipeline
        always_run: true
        context: pr-build
        labels:
          aadpodidbinding: tekton-bot
        name: pr-build
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jstrachan/jx-demo-gke2-dev: merge
        jstrachan/my-boot-jenkins: merge
        jstrachan/nodey534: merge
        jstrachan/nodey536: merge
        jstrachan/nodey545: merge
        jstrachan/nodey546: merge
        jstrachan/nodey553: merge
        jstrachan/nodey554: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx-demo-gke2-dev
        - jstrachan/my-boot-jenkins
        - jstrachan/nodey534
        - jstrachan/nodey536
        - jstrachan/nodey545
        - jstrachan/nodey546
        - jstrachan/nodey553
        - jstrachan/nodey554
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx-demo-gke2-dev
        - jstrachan/my-boot-jenkins
        - jstrachan/nodey534
        - jstrachan/nodey536
        - jstrachan/nodey545
        - jstrachan/nodey546
        - jstrachan/nodey553
        - jstrachan/nodey554
      target_url: http://dashboard-jx.34.105.246.143.xip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
