# Source: jenkins/templates/jcasc-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jenkins-config-jxsetup
  namespace: myjenkins8
  labels:
    "app.kubernetes.io/name": jenkins
    "helm.sh/chart": "jenkins-3.0.14"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
    jenkins-jenkins-config: "true"
    gitops.jenkins-x.io/pipeline: 'namespaces'
data:
  jxsetup.yaml: "jobs:\n  - script: |\n      // from template: versionStream/jenkins/templates/folder.gotmpl\n      folder('jstrachan')\n                    \n      // from template: versionStream/jenkins/templates/job.gotmpl\n      multibranchPipelineJob('jstrachan/my-boot-jenkins') {\n          branchSources {\n              github {\n                  id('jstrachan-my-boot-jenkins')\n                  scanCredentialsId('tekton-git')\n                  repoOwner('jstrachan')\n                  repository('my-boot-jenkins')\n              }\n          }\n      }"
