# Source: nodey546/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-27T09:45:43Z"
  deletionTimestamp: null
  name: 'nodey546-1.0.3'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 1.0.3
      sha: 4117e9521d88f24f3286ddf27a7e1b83ba897478
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: e024c17836f52520ae98746fad990a3cb994bef1
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        chore: upgrade pipelines
      sha: be6de2a1df661e45faffd31f189e0b67e182fc27
  gitHttpUrl: https://github.com/jstrachan/nodey546
  gitOwner: jstrachan
  gitRepository: nodey546
  name: 'nodey546'
  releaseNotesURL: https://github.com/jstrachan/nodey546/releases/tag/v1.0.3
  version: v1.0.3
status: {}
