# Source: nodey546/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-02T10:55:03Z"
  deletionTimestamp: null
  name: 'nodey546-1.0.13'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 1.0.13
      sha: 2783ce45d9635c2d1b0bd5cacf1001db2dd20b29
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 7793006f608d2eb93cd9e71e9f1debc8441f28fd
  gitHttpUrl: https://github.com/jstrachan/nodey546
  gitOwner: jstrachan
  gitRepository: nodey546
  name: 'nodey546'
  releaseNotesURL: https://github.com/jstrachan/nodey546/releases/tag/v1.0.13
  version: v1.0.13
status: {}
