filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-production
repositories:
- name: dev
  url: https://jstrachan.github.io/nodey545/
releases:
- chart: dev/nodey545
  version: 3.0.62
  name: nodey545
templates: {}
renderedvalues: {}
