# Source: rust-demo3/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-04T11:22:18Z"
  deletionTimestamp: null
  name: 'rust-demo3-0.0.5'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.5
      sha: 907695cfd8f2ac025208a7000b1e19c34d356eb3
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: b315ae7c16d2d37ee243ae37a817103ca0a78376
  gitHttpUrl: https://github.com/jstrachan/rust-demo3
  gitOwner: jstrachan
  gitRepository: rust-demo3
  name: 'rust-demo3'
  releaseNotesURL: https://github.com/jstrachan/rust-demo3/releases/tag/v0.0.5
  version: v0.0.5
status: {}
