# Source: rust-demo3/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-17T18:04:32Z"
  deletionTimestamp: null
  name: 'rust-demo3-0.0.7'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.7
      sha: cc76aa7cb8cdb2acca0667da87822a2d898800f1
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: e2f1ae87faef0dcccb403f136221076128860098
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update README.md
      sha: dbb167af72a3b582d622cee6f1b69d18604585d4
  gitHttpUrl: https://github.com/jstrachan/rust-demo3
  gitOwner: jstrachan
  gitRepository: rust-demo3
  name: 'rust-demo3'
  releaseNotesURL: https://github.com/jstrachan/rust-demo3/releases/tag/v0.0.7
  version: v0.0.7
status: {}
