# Source: jx-slack/templates/slack-token-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jx-slack
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
    - name: token
      key: jstrachan-tekton2-jx-slack
      property: token
      version: latest
  template:
    type: Opaque
