# Source: jx-slack/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-22T09:34:09Z"
  deletionTimestamp: null
  name: 'jx-slack-0.0.49'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        chore: smaller base image
      sha: 44af5ca3a1f9ddb7eccf70780112508c71e7b71c
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        chore: fix git clone
      sha: 2e77321448cb977e2f0dec66e7d87c55a7e18a45
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        chore: fix git clone
      sha: 1ec6d60180b8ffa7006071be9db3b15ac8c658cf
  gitHttpUrl: https://github.com/jenkins-x-plugins/jx-slack
  gitOwner: jenkins-x-plugins
  gitRepository: jx-slack
  name: 'jx-slack'
  version: 0.0.49
status: {}
