# Source: jx-slack/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jx-slack-jx-slack
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jx-slack-jx-slack
subjects:
  - kind: ServiceAccount
    name: jx-slack-jx-slack
