# Source: jenkins-resources/templates/pipelineactivity-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-pipeline-activity
  namespace: myjenkins7
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - pipelineactivities
      - sourcerepositories
    verbs:
      - list
      - get
      - watch
      - create
      - update
      - patch
