# Source: jenkins-resources/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-18T15:12:04Z"
  deletionTimestamp: null
  name: 'jenkins-resources-0.0.2'
  namespace: myjenkins7
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: a2fa64c8032d434b631542bec438c888e88cb6df
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: add roles for being able to modify PipelineActivity resources
      sha: 38f0762178dc131b0002240c4ae1c29daff589c9
  gitCloneUrl: https://github.com/jenkins-x-charts/jenkins-resources.git
  gitHttpUrl: https://github.com/jenkins-x-charts/jenkins-resources
  gitOwner: jenkins-x-charts
  gitRepository: jenkins-resources
  name: 'jenkins-resources'
  releaseNotesURL: https://github.com/jenkins-x-charts/jenkins-resources/releases/tag/v0.0.2
  version: v0.0.2
status: {}
