# Source: harbor/templates/notary/notary-secret-envvars.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: harbor-notary-server-envvars
  labels:
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-9.6.1
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: notary
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
    - name: server_db_url
      key: jstrachan-tekton2-harbor-notary-server-envvars
      property: server_db_url
      version: latest
    - name: signer_db_url
      key: jstrachan-tekton2-harbor-notary-server-envvars
      property: signer_db_url
      version: latest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harbor
        helm.sh/chart: harbor-9.6.1
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: notary
    type: Opaque
