# Source: harbor/templates/core/core-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core
  labels:
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-9.6.1
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: core
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
    - name: secretKey
      key: jstrachan-tekton2-harbor-core
      property: secretKey
      version: latest
    - name: secret
      key: jstrachan-tekton2-harbor-core
      property: secret
      version: latest
    - name: tls.crt
      key: jstrachan-tekton2-harbor-core
      property: tls.crt
      version: latest
    - name: tls.key
      key: jstrachan-tekton2-harbor-core
      property: tls.key
      version: latest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harbor
        helm.sh/chart: harbor-9.6.1
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: core
    type: Opaque
