# Source: harbor/templates/core/core-secret-envvars.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-envvars
  labels:
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-9.6.1
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: core
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
    - name: _REDIS_URL_CORE
      key: jstrachan-tekton2-harbor-core-envvars
      property: _REDIS_URL_CORE
      version: latest
    - name: _REDIS_URL_REG
      key: jstrachan-tekton2-harbor-core-envvars
      property: _REDIS_URL_REG
      version: latest
    - name: REGISTRY_CREDENTIAL_USERNAME
      key: jstrachan-tekton2-harbor-core-envvars
      property: REGISTRY_CREDENTIAL_USERNAME
      version: latest
    - name: REGISTRY_CREDENTIAL_PASSWORD
      key: jstrachan-tekton2-harbor-core-envvars
      property: REGISTRY_CREDENTIAL_PASSWORD
      version: latest
    - name: CSRF_KEY
      key: jstrachan-tekton2-harbor-core-envvars
      property: CSRF_KEY
      version: latest
    - name: HARBOR_ADMIN_PASSWORD
      key: jstrachan-tekton2-harbor-core-envvars
      property: HARBOR_ADMIN_PASSWORD
      version: latest
    - name: POSTGRESQL_PASSWORD
      key: jstrachan-tekton2-harbor-core-envvars
      property: POSTGRESQL_PASSWORD
      version: latest
    - name: CLAIR_DB_PASSWORD
      key: jstrachan-tekton2-harbor-core-envvars
      property: CLAIR_DB_PASSWORD
      version: latest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harbor
        helm.sh/chart: harbor-9.6.1
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: core
    type: Opaque
