apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: jstrachan
    provider: https://github.com
    providerKind: github
    repositories:
    - name: bdd-gh-1612282705
    - name: bdd-gh-1612284286
    - name: my-boot-jenkins
    - name: nodey534
    - name: nodey536
    - name: nodey545
    - name: nodey546
    - name: nodey553
    - name: nodey554
    scheduler: in-repo
  jenkinsServers:
  - groups:
    - owner: jstrachan
      provider: https://github.com
      providerKind: github
      repositories:
      - name: my-boot-jenkins
    server: myjenkinsa
