# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry
  labels:
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-9.6.1
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd1
  data:
    - name: REGISTRY_HTPASSWD
      key: jstrachan-tekton3-harbor-registry
      property: REGISTRY_HTPASSWD
      version: latest
    - name: REGISTRY_HTTP_SECRET
      key: jstrachan-tekton3-harbor-registry
      property: REGISTRY_HTTP_SECRET
      version: latest
    - name: REGISTRY_REDIS_PASSWORD
      key: jstrachan-tekton3-harbor-registry
      property: REGISTRY_REDIS_PASSWORD
      version: latest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harbor
        helm.sh/chart: harbor-9.6.1
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/managed-by: Helm
    type: Opaque
