filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jenkins
repositories:
- name: jenkinsci
  url: https://charts.jenkins.io
releases:
- chart: jenkinsci/jenkins
  name: jenkins
  values:
  - ../../versionStream/charts/jenkinsci/jenkins/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
