# Source: jenkins/templates/jcasc-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jenkins-config-jxsetup
  namespace: cheese
  labels:
    "app.kubernetes.io/name": jenkins
    "helm.sh/chart": "jenkins-3.0.9"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
    jenkins-jenkins-config: "true"
    gitops.jenkins-x.io/pipeline: 'namespaces'
data:
  jxsetup.yaml: "jobs:\n  - script: |\n      // from template: versionStream/jenkins/templates/folder.gotmpl\n      folder('jstrachan')\n                    \n      // from template: versionStream/jenkins/templates/job.gotmpl\n      multibranchPipelineJob('jstrachan/hello-world-jenkinsfile') {\n          branchSources {\n              git {\n                  id = 'jstrachan-hello-world-jenkinsfile'\n                  remote('https://github.com/jstrachan/hello-world-jenkinsfile.git')\n              }\n          }\n      }\n                    \n      // from template: versionStream/jenkins/templates/job.gotmpl\n      multibranchPipelineJob('jstrachan/spring-boot-maven-jenkinsfile') {\n          branchSources {\n              git {\n                  id = 'jstrachan-spring-boot-maven-jenkinsfile'\n                  remote('https://github.com/jstrachan/spring-boot-maven-jenkinsfile.git')\n              }\n          }\n      }"
