# Source: nodey560/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    beer: stella
    kubernetes.io/ingress.class: nginx
    wine: shiraz
  name: nodey560
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: nodey560
              servicePort: 80
      host: nodey560-jx-staging.35.246.77.80.nip.io
