# Source: jenkins/templates/jcasc-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jenkins-config-mysetup
  namespace: myjenkins
  labels:
    "app.kubernetes.io/name": jenkins
    "helm.sh/chart": "jenkins-3.0.8"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
    jenkins-jenkins-config: "true"
    gitops.jenkins-x.io/pipeline: 'namespaces'
data:
  mysetup.yaml: |-
    jenkins:
      systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
    jobs:
      - script: |
          multibranchPipelineJob('configuration-as-code') {
              branchSources {
                  git {
                      id = 'jstrachan-hello-world-jenkinsfile'
                      remote('https://github.com/jstrachan/hello-world-jenkinsfile.git')
                  }
              }
          }
