# Source: rust-demo3/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-22T10:34:05Z"
  deletionTimestamp: null
  name: 'rust-demo3-0.0.10'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.10
      sha: c6dc6d57f05961b0cd0edfa174d535153e49e1a6
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 13fa02396de2e2f1bb1abb08c7e23d75be4cdef4
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update Dockerfile
      sha: 72dbc7fe26c9fe03f6cf734e17945948d940a5e8
  gitHttpUrl: https://github.com/jstrachan/rust-demo3
  gitOwner: jstrachan
  gitRepository: rust-demo3
  name: 'rust-demo3'
  releaseNotesURL: https://github.com/jstrachan/rust-demo3/releases/tag/v0.0.10
  version: v0.0.10
status: {}
