# Source: rust-demo3/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-22T09:46:29Z"
  deletionTimestamp: null
  name: 'rust-demo3-0.0.8'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.8
      sha: f2faded48c876c5817a6665687c7791ae81b28be
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: c9ad5582f5fc0a9c32a7e423c3b934ee8d8a1182
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update Dockerfile
      sha: 260409aa500b1c47d51c77eaec325f1fee2fd8e1
  gitHttpUrl: https://github.com/jstrachan/rust-demo3
  gitOwner: jstrachan
  gitRepository: rust-demo3
  name: 'rust-demo3'
  releaseNotesURL: https://github.com/jstrachan/rust-demo3/releases/tag/v0.0.8
  version: v0.0.8
status: {}
