# Source: nodey554/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-21T14:46:07Z"
  deletionTimestamp: null
  name: 'nodey554-1.0.14'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 1.0.14
      sha: efb423df19002bed4eba20cc2ef63849a1357dc1
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 1cf85bb99c5454637a32354d156e2c5be598ff55
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update index.html
      sha: 2187121e32e490e7f05a4d66671f8aa858f84041
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update index.html
      sha: 4a87f924c21409143f6e88178abcca553a1549b8
  gitHttpUrl: https://github.com/jstrachan/nodey554
  gitOwner: jstrachan
  gitRepository: nodey554
  name: 'nodey554'
  releaseNotesURL: https://github.com/jstrachan/nodey554/releases/tag/v1.0.14
  version: v1.0.14
status: {}
