# Source: nodey554/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-21T12:19:15Z"
  deletionTimestamp: null
  name: 'nodey554-1.0.12'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 1.0.12
      sha: 03cb967159c2fa557c7148fdcdc954a98d25c3e7
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 65a751820df01491a3104f2e6e446572751bdef1
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update index.html
      sha: 8fd374182342fa220bf2c39ea5a53b90d09f0d4e
  gitHttpUrl: https://github.com/jstrachan/nodey554
  gitOwner: jstrachan
  gitRepository: nodey554
  name: 'nodey554'
  releaseNotesURL: https://github.com/jstrachan/nodey554/releases/tag/v1.0.12
  version: v1.0.12
status: {}
