# Source: lighthouse/templates/foghorn-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-foghorn
  labels:
    draft: draft-app
    chart: "lighthouse-0.0.922"
    app: lighthouse-foghorn
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    wave.pusher.com/update-on-config-change: 'true'
    jenkins-x.io/hash: '68e5f7fa775902afbebe5f6ace1c809200202d0e964ba6d8f3b12054d117c0fa'
spec:
  replicas: 1
  selector:
    matchLabels:
      draft: draft-app
      app: lighthouse-foghorn
  template:
    metadata:
      labels:
        draft: draft-app
        app: lighthouse-foghorn
    spec:
      serviceAccountName: lighthouse-foghorn
      containers:
        - name: lighthouse-foghorn
          image: gcr.io/jenkinsxio/lighthouse-foghorn:0.0.922
          imagePullPolicy: IfNotPresent
          args:
            - "--namespace=jx"
          env:
            - name: "GIT_KIND"
              value: "github"
            - name: "GIT_SERVER"
              value: "https://github.com"
            - name: "GIT_USER"
              value: jstrachan
            - name: "GIT_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: lighthouse-oauth-token
                  key: oauth
            - name: "HMAC_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: "lighthouse-hmac-token"
                  key: hmac
            - name: "JX_LOG_FORMAT"
              value: "json"
            - name: "LOGRUS_FORMAT"
              value: "json"
            - name: DEFAULT_PIPELINE_RUN_SERVICE_ACCOUNT
              value: "tekton-bot"
            - name: DEFAULT_PIPELINE_RUN_TIMEOUT
              value: "2h0m0s"
            - name: FILE_BROWSER
              value: "git"
            - name: JX_DEFAULT_IMAGE
              value: "gcr.io/jenkinsxio/builder-maven:2.1.142-761"
            - name: LIGHTHOUSE_DASHBOARD_TEMPLATE
              value: "namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}"
            - name: LIGHTHOUSE_VERSIONSTREAM_JENKINS_X_JX3_PIPELINE_CATALOG
              value: "9f668d7067518765fcca54f580066a673444af39"
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds: 180
